name: Move Issue to QA Board

on:
  issues:
    types: [labeled]

jobs:
  add-to-qa-board:
    if: github.event.label.name == 'ready-for-qa'
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to QA Project (Beta)
        uses: peter-evans/add-to-project@v1
        with:
          project-url: https://github.com/users/btswann11/projects/2
          github-token: ${{ secrets.TOKEN }}
          content-id: ${{ github.event.issue.node_id }}
