name: Move Issue to QA Board

on:
  project_card:
    types: [moved]

jobs:
  sync-to-qa:
    runs-on: ubuntu-latest
    if: github.event.project_card.column_name == 'Ready for QA'
    steps:
      - name: Add issue to QA project
        uses: peter-evans/add-to-project@v1
        with:
          project-url: https://github.com/users/btswann11/projects/1
          github-token: ${{ secrets.TOKEN }}
          content-id: ${{ github.event.project_card.content_id }}
          content-type: ISSUE
